"""empty message

Revision ID: 1768eb29c1e0
Revises: c8b9ecc70127
Create Date: 2016-02-28 22:13:49.935232

"""

# revision identifiers, used by Alembic.
revision = '1768eb29c1e0'
down_revision = 'c8b9ecc70127'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zbhost', sa.Column('host', sa.String(length=50), nullable=True))
    op.add_column('zbhost', sa.Column('hostid', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_zbhost_hostid'), 'zbhost', ['hostid'], unique=True)
    op.drop_index('ix_zbhost_status', table_name='zbhost')
    op.drop_index('ix_zbhost_zb_hostid', table_name='zbhost')
    op.drop_column('zbhost', 'status')
    op.drop_column('zbhost', 'zb_hostid')
    op.drop_column('zbhost', 'hostname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zbhost', sa.Column('hostname', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('zbhost', sa.Column('zb_hostid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('zbhost', sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_zbhost_zb_hostid', 'zbhost', ['zb_hostid'], unique=True)
    op.create_index('ix_zbhost_status', 'zbhost', ['status'], unique=False)
    op.drop_index(op.f('ix_zbhost_hostid'), table_name='zbhost')
    op.drop_column('zbhost', 'hostid')
    op.drop_column('zbhost', 'host')
    ### end Alembic commands ###
