"""empty message

Revision ID: 5f219f7c222c
Revises: None
Create Date: 2016-01-22 03:24:49.559190

"""

# revision identifiers, used by Alembic.
revision = '5f219f7c222c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=False),
    sa.Column('power', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinet_idc_id'), 'cabinet', ['idc_id'], unique=False)
    op.create_table('idc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('idc_name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('user_interface', sa.String(length=50), nullable=True),
    sa.Column('user_phone', sa.String(length=50), nullable=True),
    sa.Column('rel_cabinet_num', sa.Integer(), nullable=True),
    sa.Column('pact_cabinet_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idc_name'), 'idc', ['name'], unique=False)
    op.create_table('ip_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_type', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('mac', sa.String(length=50), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('server_port', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iptype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('management_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('m_type')
    )
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('power',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_power', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_power')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_name', sa.String(length=50), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('module_letter', sa.String(length=15), nullable=False),
    sa.Column('dev_interface', sa.String(length=100), nullable=False),
    sa.Column('op_interface', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_pid'), 'product', ['pid'], unique=False)
    op.create_table('raid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raidtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reboot_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=400), nullable=True),
    sa.Column('manufacturers', sa.String(length=200), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('server_type', sa.String(length=50), nullable=True),
    sa.Column('st', sa.String(length=50), nullable=True),
    sa.Column('assets_no', sa.String(length=50), nullable=True),
    sa.Column('idc_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('cabinet_pos', sa.String(length=15), nullable=True),
    sa.Column('expire', sa.Date(), nullable=True),
    sa.Column('ups', sa.Integer(), nullable=True),
    sa.Column('parter', sa.String(length=50), nullable=True),
    sa.Column('parter_type', sa.String(length=50), nullable=True),
    sa.Column('server_up_time', sa.Date(), nullable=True),
    sa.Column('os_type', sa.String(length=30), nullable=True),
    sa.Column('os_version', sa.String(length=30), nullable=True),
    sa.Column('hostname', sa.String(length=30), nullable=True),
    sa.Column('inner_ip', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('ipinfo', sa.String(length=50), nullable=True),
    sa.Column('server_cpu', sa.String(length=50), nullable=True),
    sa.Column('server_mem', sa.String(length=50), nullable=True),
    sa.Column('raid', sa.String(length=50), nullable=True),
    sa.Column('raid_card_type', sa.String(length=50), nullable=True),
    sa.Column('remote_card', sa.String(length=50), nullable=True),
    sa.Column('remote_cardip', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('last_op_time', sa.DateTime(), nullable=True),
    sa.Column('last_op_people', sa.Integer(), nullable=False),
    sa.Column('monitor_mail_group', sa.String(length=50), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('server_purpose', sa.Integer(), nullable=True),
    sa.Column('trouble_resolve', sa.Integer(), nullable=True),
    sa.Column('op_interface_other', sa.Integer(), nullable=True),
    sa.Column('dev_interface', sa.Integer(), nullable=True),
    sa.Column('check_update_time', sa.DateTime(), nullable=True),
    sa.Column('vm_status', sa.Integer(), nullable=True),
    sa.Column('power', sa.String(length=30), nullable=True),
    sa.Column('host', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_cabinet_id'), 'server', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_server_hostname'), 'server', ['hostname'], unique=False)
    op.create_index(op.f('ix_server_idc_id'), 'server', ['idc_id'], unique=False)
    op.create_index(op.f('ix_server_inner_ip'), 'server', ['inner_ip'], unique=False)
    op.create_index(op.f('ix_server_os_type'), 'server', ['os_type'], unique=False)
    op.create_index(op.f('ix_server_os_version'), 'server', ['os_version'], unique=False)
    op.create_index(op.f('ix_server_uuid'), 'server', ['uuid'], unique=False)
    op.create_index(op.f('ix_server_vm_status'), 'server', ['vm_status'], unique=False)
    op.create_table('server_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('manufacturers_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_type_manufacturers_id'), 'server_type', ['manufacturers_id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=50), nullable=False),
    sa.Column('switch_type', sa.String(length=50), nullable=False),
    sa.Column('manager_ip', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('expire', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('manufacturers', sa.String(length=50), nullable=False),
    sa.Column('last_op_time', sa.Date(), nullable=True),
    sa.Column('last_op_people', sa.String(length=30), nullable=False),
    sa.Column('switch_port_nums', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_department_id'), 'user', ['department_id'], unique=False)
    op.create_index(op.f('ix_user_is_leader'), 'user', ['is_leader'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.create_table('zbhost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cmdb_hostid', sa.Integer(), nullable=True),
    sa.Column('zb_hostid', sa.Integer(), nullable=True),
    sa.Column('hostname', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zbhost_cmdb_hostid'), 'zbhost', ['cmdb_hostid'], unique=True)
    op.create_index(op.f('ix_zbhost_status'), 'zbhost', ['status'], unique=False)
    op.create_index(op.f('ix_zbhost_zb_hostid'), 'zbhost', ['zb_hostid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zbhost_zb_hostid'), table_name='zbhost')
    op.drop_index(op.f('ix_zbhost_status'), table_name='zbhost')
    op.drop_index(op.f('ix_zbhost_cmdb_hostid'), table_name='zbhost')
    op.drop_table('zbhost')
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_is_leader'), table_name='user')
    op.drop_index(op.f('ix_user_department_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('switch')
    op.drop_table('supplier')
    op.drop_table('status')
    op.drop_index(op.f('ix_server_type_manufacturers_id'), table_name='server_type')
    op.drop_table('server_type')
    op.drop_index(op.f('ix_server_vm_status'), table_name='server')
    op.drop_index(op.f('ix_server_uuid'), table_name='server')
    op.drop_index(op.f('ix_server_os_version'), table_name='server')
    op.drop_index(op.f('ix_server_os_type'), table_name='server')
    op.drop_index(op.f('ix_server_inner_ip'), table_name='server')
    op.drop_index(op.f('ix_server_idc_id'), table_name='server')
    op.drop_index(op.f('ix_server_hostname'), table_name='server')
    op.drop_index(op.f('ix_server_cabinet_id'), table_name='server')
    op.drop_table('server')
    op.drop_table('reboot_test')
    op.drop_table('raidtype')
    op.drop_table('raid')
    op.drop_index(op.f('ix_product_pid'), table_name='product')
    op.drop_table('product')
    op.drop_table('power')
    op.drop_table('manufacturers')
    op.drop_table('management_card')
    op.drop_table('iptype')
    op.drop_table('ip_info')
    op.drop_index(op.f('ix_idc_name'), table_name='idc')
    op.drop_table('idc')
    op.drop_index(op.f('ix_cabinet_idc_id'), table_name='cabinet')
    op.drop_table('cabinet')
    ### end Alembic commands ###
