"""empty message

Revision ID: 87067751bf43
Revises: b1b08aeec8c7
Create Date: 2016-02-02 16:57:09.776515

"""

# revision identifiers, used by Alembic.
revision = '87067751bf43'
down_revision = 'b1b08aeec8c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_idc_name', table_name='idc')
    op.create_index(op.f('ix_idc_name'), 'idc', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idc_name'), table_name='idc')
    op.create_index('ix_idc_name', 'idc', ['name'], unique=False)
    ### end Alembic commands ###
