"""empty message

Revision ID: 8daafb6ce0d7
Revises: 1768eb29c1e0
Create Date: 2016-02-29 00:59:08.282889

"""

# revision identifiers, used by Alembic.
revision = '8daafb6ce0d7'
down_revision = '1768eb29c1e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_hostname', table_name='server')
    op.create_index(op.f('ix_server_hostname'), 'server', ['hostname'], unique=True)
    op.drop_index('ix_server_inner_ip', table_name='server')
    op.create_index(op.f('ix_server_inner_ip'), 'server', ['inner_ip'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_inner_ip'), table_name='server')
    op.create_index('ix_server_inner_ip', 'server', ['inner_ip'], unique=False)
    op.drop_index(op.f('ix_server_hostname'), table_name='server')
    op.create_index('ix_server_hostname', 'server', ['hostname'], unique=False)
    ### end Alembic commands ###
