"""empty message

Revision ID: 93c92c0ca6c9
Revises: 87067751bf43
Create Date: 2016-02-04 00:38:30.675353

"""

# revision identifiers, used by Alembic.
revision = '93c92c0ca6c9'
down_revision = '87067751bf43'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cabinet', ['name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cabinet', type_='unique')
    ### end Alembic commands ###
