"""empty message

Revision ID: b1b08aeec8c7
Revises: 5f219f7c222c
Create Date: 2016-02-02 16:40:36.627554

"""

# revision identifiers, used by Alembic.
revision = 'b1b08aeec8c7'
down_revision = '5f219f7c222c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idc', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('idc', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('idc', 'pact_cabinet_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('idc', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=False)
    op.alter_column('idc', 'rel_cabinet_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('idc', 'user_interface',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('idc', 'user_phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('idc', 'user_phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('idc', 'user_interface',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('idc', 'rel_cabinet_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('idc', 'phone',
               existing_type=mysql.VARCHAR(length=25),
               nullable=True)
    op.alter_column('idc', 'pact_cabinet_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('idc', 'email',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('idc', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###
