"""empty message

Revision ID: c8b9ecc70127
Revises: d4b0413fe8b2
Create Date: 2016-02-12 03:33:01.346985

"""

# revision identifiers, used by Alembic.
revision = 'c8b9ecc70127'
down_revision = 'd4b0413fe8b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('server_disk', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'server_disk')
    ### end Alembic commands ###
